Revisit upgrade process

diff --git a/rootfs/upgrade/upgrade-rootfs b/rootfs/upgrade/upgrade-rootfs
--- a/rootfs/upgrade/upgrade-rootfs
+++ b/rootfs/upgrade/upgrade-rootfs
@@ -5,6 +5,14 @@
 
 Error() { echo >&2 "$@"; exit 1; }
 
+# Retrieve named file from TFTP server
+tftp_get()
+{
+    echo "Reading $1 from $TFTP_SERVER ($serverip)"
+    tftp -g -l $TEMPFILE -r "$TFTP_PREFIX"$1 $serverip  ||
+        Error "Unable to read $TFTP_PREFIX$1"
+}
+
 
 TFTP_PREFIX=/
 TFTP_SERVER=none
@@ -13,37 +21,37 @@ TFTP_SERVER=none
 [ -e /etc/upgrade.config ]  &&
 source /etc/upgrade.config
 
-UPGRADE_ROOTFS=false
-UPGRADE_KERNEL=false
-UPGRADE_DTS=false
+UPGRADE_STATE=0
+TEST_FILES=true
+CONFIRM=false
+REBOOT_NOW=false
 
 # Process options
-while getopts 'P:S:rkdh' option; do
+while getopts 'P:S:prfCh' option; do
     case "$option" in
         P)  TFTP_PREFIX="$OPTARG" ;;
         S)  TFTP_SERVER="$OPTARG" ;;
-        r)  UPGRADE_ROOTFS=true ;;
-        k)  UPGRADE_KERNEL=true ;;
-        d)  UPGRADE_DTS=true ;;
+        p)  UPGRADE_STATE=1 ;;
+        f)  TEST_FILES=false ;;
+        r)  REBOOT_NOW=true ;;
+        C)  CONFIRM=true ;;
         h)  cat <<EOF
-Usage: upgrade-rootfs server-ip:
+Usage: upgrade-rootfs [options]
+
 Configures upgrade of root file system from tftp server.
     -P: Specify TFTP prefix (default is $TFTP_PREFIX)
     -S: Specify TFTP server (default is $TFTP_SERVER)
-    -k  Upgrade kernel (${TFTP_PREFIX}zImage must be present on server)
-    -d  Upgrade device tree (${TFTP_PREFIX}device-tree.dtb must be present on
-        server)
-    -r  Upgrade rootfs (${TFTP_PREFIX}upgrade-script.image and
-        ${TFTP_PREFIX}rootfs.img must be present on server)
+    -p  If this flag is set then the persistent state will be replaced.
+    -f  This flag can be set to bypass validation of the upgrade files on the
+        tftp server.
+    -r  If set then reboot will be triggered immediately.
+    -C  This flag must be set to confirm the upgrade, otherwise the upgrade will
+        be tested but not actually applied.
 EOF
             exit 0 ;;
         *)  Error 'Invalid option: try -h for help' ;;
     esac
 done
-
-# Ensure that we've got something to do
-$UPGRADE_ROOTFS || $UPGRADE_KERNEL || $UPGRADE_DTS ||
-    Error Must specify at least one target to upgrade
 
 
 # Normalise the server name and check it is responding
@@ -51,32 +59,24 @@ set -o pipefail
 serverip="$(getent hosts "$TFTP_SERVER" | sed 's/ .*//')"  ||
     Error Unable to look up TFTP server "$TFTP_SERVER"
 
-# Retrieve named file from TFTP server
-tftp_get()
-{
-    echo "Reading $1 from $TFTP_SERVER ($serverip)"
-    tftp -g -l /tmp/$1 -r "$TFTP_PREFIX"$1 $serverip  ||
-        Error "Unable to read $TFTP_PREFIX$1"
-}
 
+# Check that we can read all the requested files
+if $TEST_FILES; then
+    TEMPFILE=$(mktemp)
+    trap 'rm -f $TEMPFILE' EXIT
 
-# We can do the kernel and device tree upgrades here and now.
-if $UPGRADE_KERNEL; then
+    echo Validating upgrade files on TFTP server
     tftp_get zImage
-    ubiupdatevol /dev/ubi0_0 /tmp/device-tree.dtb
-fi
-
-if $UPGRADE_DTS; then
     tftp_get device-tree.dtb
-    ubiupdatevol /dev/ubi0_1 /tmp/device-tree.dtb
+    tftp_get rootfs.img
+    if [ $UPGRADE_STATE = 1 ]; then
+        tftp_get state.img
+    fi
 fi
 
 
 # We need to hand control over to u-boot to do the rootfs upgrade.
-if $UPGRADE_ROOTFS; then
-    # Check that the upgrade script is present on the TFTP server, fail if not.
-    tftp_get upgrade-script.image
-
+if $CONFIRM; then
     # Pick up our ethernet configuration
     ipaddr=$(ifconfig eth0 | sed -n '/.* addr:/{s///; s/ .*//; p;q}')
     netmask=$(ifconfig eth0 | sed -n '/.* Mask:/{s///; s/ .*//; p;q}')
@@ -89,10 +89,11 @@ netmask $netmask
 gatewayip $gatewayip
 serverip $serverip
 server_prefix $TFTP_PREFIX
+write_state $UPGRADE_STATE
 bootcmd tftpboot \$scriptaddr \${server_prefix}upgrade-script.image  &&  \
 source \$scriptaddr
 EOF
     fw_setenv -s /dev/stdin  &&
     # Go!
-    reboot
+    $REBOOT_NOW  &&  reboot
 fi
